### ISSUE TITLE
Doesn't work when copilot is disabled

### ISSUE THREAD

**Issue by Hubro** [ofseed/copilot-status.nvim#3]
I have copilot disabled, meaning I only get suggestions when I manually require it. In other words:

```lua
vim.g.copilot_filetypes = { ["*"] = false }
vim.keymap.set("i", "<A-p>", "<Plug>(copilot-suggest)", { silent = true })
vim.keymap.set("i", "<A-j>", "<Plug>(copilot-next)", { silent = true })
vim.keymap.set("i", "<A-k>", "<Plug>(copilot-previous)", { silent = true })
```

This works, but copilot-status.nvim doesn't work because it checks if copilot is enabled, then does nothing.

It would be nice if the status spinner worked even if Copilot is disabled.

**Comment by ofseed** [comment]
Done.
