### ISSUE TITLE
Status not detecting enabled copilot

### ISSUE THREAD

**Issue by AndreM222** [ofseed/copilot-status.nvim#4]
Am I doing something wrong that keeps saying is not enabled?

![image](https://github.com/ofseed/copilot-status.nvim/assets/98118238/359309c9-cc46-452c-9933-1fb7b76cfeba)

![image](https://github.com/ofseed/copilot-status.nvim/assets/98118238/28335240-ba8f-4a12-8cc9-b63d2fac8904)

![image](https://github.com/ofseed/copilot-status.nvim/assets/98118238/d48036f2-f98c-44ea-94e8-7724bb34f563)

**Comment by ofseed** [comment]
It seems that you are using copilot.lua instead of copilot.vim. This plugin is only supports copilot.vim now, even support for copilot.lua is also being planned.

**Comment by AndreM222** [comment]
Thanks for the answer 👌👌👌
